python search_multinomial.py  \
--data 'VOC' \
--arch_type 'V1+SSD' \
--ActQ 'LSQ+' \
--num_classes 21 \
--finetune_only \
--cv_dir '/SHARE_ST/capp_storage/jeesak_dir/InstaNasWACV/MBv1-SSD/fine-tune' \
--instassd_chkpt '/SHARE_ST/capp_storage/jeesak_dir/InstaNasWACV/MBv1-SSD/search/latest.pth.tar' \
--agent_chkpt '/SHARE_ST/capp_storage/jeesak_dir/InstaNasWACV/MBv1-SSD/search/latest.pth.tar' \
--retraining 'True' \
--resume \
--sample_eval_path './prec_thre06/sample_eval_test' \
--search_eval_path './prec_thre06/search_eval_test' \
--eval_path './prec_thre06/eval_test' \
--extras_wbit 4 \
--extras_abit 4 \
--head_wbit 8 \
--head_abit 8 \
--input_norm 'True' \
--agent_lr_type 'cosine'  \
--full_pretrain 'False' \
--lr_type 'cosine' \
--optimizer 'sgd' \
--image_size 300 \
--plot_result \
--abit 4 \
--action_list 3 4 5 \
--lr 1e-5 --batch_size 64 --epochs 300 --gpu '0' 